on:
  push:
    tags:
      - 'v*'
name: Create Release

jobs:
  create_release:
    name: Create new release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          ref: ${{ github.ref }}
      - name: Create Release
        run: |
          bash tools/create_release.sh ${{ github.ref_name }}
  build_for_macosx:
    needs: [create_release]
    name: Build for MacOSX
    runs-on: macos-13
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          ref: ${{github.ref}}
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.9'
      - name: Build
        run: |
          TAG=${{ github.ref_name }}
          VERSION=${TAG#v}
          CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags "-X 'main.Version=${VERSION}'" -o out/go-auto-build-sample main.go
          tar zcvf out/go-auto-build-sample-macosx-${VERSION}-amd64.tgz -C out go-auto-build-sample
          bash tools/upload_asset.sh ${VERSION} out/go-auto-build-sample-macosx-${VERSION}-amd64.tgz
          cp out/go-auto-build-sample out/go-auto-build-sample.amd64
          CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -ldflags "-X 'main.Version=${VERSION}'" -o out/go-auto-build-sample main.go
          tar zcvf out/go-auto-build-sample-macosx-${VERSION}-arm64.tgz -C out go-auto-build-sample
          bash tools/upload_asset.sh ${VERSION} out/go-auto-build-sample-macosx-${VERSION}-arm64.tgz
          cp out/go-auto-build-sample out/go-auto-build-sample.arm64
          lipo -output out/go-auto-build-sample -create out/go-auto-build-sample.amd64 out/go-auto-build-sample.arm64
          tar zcvf out/go-auto-build-sample-macosx-${VERSION}-universal.tgz -C out go-auto-build-sample
          bash tools/upload_asset.sh ${VERSION} out/go-auto-build-sample-macosx-${VERSION}-universal.tgz
  build_for_linux:
    needs: [create_release]
    name: Build for Linux
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          ref: ${{github.ref}}
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.9'
      - name: Build
        run: |
          TAG=${{ github.ref_name }}
          VERSION=${TAG#v}
          # build for Linux amd64
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-X 'main.Version=${VERSION}'" -o out/go-auto-build-sample main.go
          tar zcvf out/go-auto-build-sample-linux-${VERSION}-amd64.tgz -C out go-auto-build-sample
          bash tools/upload_asset.sh ${VERSION} out/go-auto-build-sample-linux-${VERSION}-amd64.tgz
          # build for Linux arm64
          CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -ldflags "-X 'main.Version=${VERSION}'" -o out/go-auto-build-sample main.go
          tar zcvf out/go-auto-build-sample-linux-${VERSION}-arm64.tgz -C out go-auto-build-sample
          bash tools/upload_asset.sh ${VERSION} out/go-auto-build-sample-linux-${VERSION}-arm64.tgz
  build_for_windows:
    needs: [create_release]
    name: Build for Windows
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          ref: ${{github.ref}}
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.9'
      - name: Build
        run: |
          $tag = "${{ github.ref_name }}"
          $version = $tag -replace 'v', ''
          $env:GOOS = "windows"
          $env:GOARCH = "amd64"
          $env:CGO_ENABLED = "0"
          go build -ldflags "-X 'main.Version=${version}'" -o ./out/go-auto-build-sample.exe main.go
          Compress-Archive -Path ./out/go-auto-build-sample.exe -DestinationPath ./out/go-auto-build-sample-windows-${version}-amd64.zip
          bash ./tools/upload_asset.sh ${version} ./out/go-auto-build-sample-windows-${version}-amd64.zip
  finish_release:
    needs: [build_for_macosx, build_for_linux, build_for_windows]
    name: Finish the release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
      ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          ref: ${{github.ref}}
      - name: Download assets and compute shasum
        run: |
          TAG=${{ github.ref_name }}
          VERSION=${TAG#v}
          bash tools/download_assets.sh ${VERSION}
          bash tools/upload_asset.sh ${VERSION} SHASUMS256.txt
          bash tools/finish_release.sh ${VERSION}
